version: "2.3"
services:
  postgres:
    image: postgres:14.13
    command: postgres -c 'max_connections=1024'
    container_name: postgres
    restart: always
    volumes:
      - falv-data-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - net
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    volumes:
      - falv-data-redis:/var/lib/redis/data
    networks:
      - net
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  migrations:
    image: $BACKEND_IMAGE
    command: python init_data.py
    container_name: migrations
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - postgres
      - redis
  backend:
    image: $BACKEND_IMAGE
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000  --workers 4
    env_file:
      - .env
    restart: always
    container_name: backend
    networks:
      - net
    ports:
      - 9000:9000
    depends_on:
      - migrations
  celery:
    image: $BACKEND_IMAGE
    command: celery -A app.core.celery worker -l INFO -c 1000 -P eventlet
    container_name: celery
    restart: always
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - migrations
  scheduler:
    image: $BACKEND_IMAGE
    command: celery -A app.core.celery beat -l info --schedule celerybeat-schedule.db
    container_name: scheduler
    restart: always
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - migrations
networks:
  net:
    name: net
    external: false
volumes:
  data-postgres:
    name: falv-data-postgres
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/falv/postgres
  data-redis:
    name: falv-data-redis
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/falv/redis